jawce:
  start-menu: "START-MENU"
  emulate: true
  history:
    file-enabled: true
    dir: "./.history"
    file-prefix: "ehailing-history"
    max-file-size-bytes: 2097152
    max-files: 10
    executor-threads: 1

whatsapp:
  hub-token: REPLACE-WITH-YOUR-WEBHOOK-VERIFICATION-TOKEN
  access-token: REPLACE-WITH-ACCESS-TOKEN
  phone-number-id: REPLACE-WITH-PHONE-NUMBER-ID
  app-secret: YOUR-APPLICATION-SECRET

server:
  servlet:
    context-path: "/chatbot"

  port: 8000

spring:
  mustache:
    check-template-location: false
  application:
    name: "ehailing-chatbot"
