resources:
  templates: classpath*:templates/**/*.{yaml,yml}
  triggers: classpath*:triggers/**/*.{yaml,yml}
  hooks:
    base-url: "http://localhost:${server.port}${server.servlet.context-path}"

chatbot:
  configs:
    hub-token: my-hub-token
    access-token: my-access-token
    phone-number-id: my-phone-number-id

server:
  servlet:
    context-path: /jawce
  port: 8080
