resources:
  templates: "classpath*:templates/**/*.{yaml,yml}"
  triggers: "classpath*:triggers/**/*.{yaml,yml}"
  hooks:
    base-url: "http://localhost:${server.port}${server.servlet.context-path}"
    security-token: "hook-url-auth-token"

chatbot:
  configs:
    cache: "file"
    initial-stage: "START-MENU"
    session-ttl: 30
    hub-token: "replace-with-your-hub-token"
    access-token: "replace-with-your-access-token"
    phone-number-id: "replace-with-your-phone-number-id"

server:
  servlet:
    context-path: /jawce
  port: 8080

spring:
  application:
    name: JAWCE-CHATBOT
